# Generated by Django 6.0 on 2026-03-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointmentslot',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('full', 'Full')], default='open', max_length=10),
        ),
    ]
