# Generated by Django 6.0.2 on 2026-04-11 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_alter_appointmentslot_status'),
    ]

    operations = [
    ]
