# Generated by Django 6.0.2 on 2026-03-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='images/hospital_pics/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='images/hospital_pics/'),
        ),
        migrations.AddField(
            model_name='hospital',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='images/hospital_pics/'),
        ),
    ]
