# Generated by Django 6.0.2 on 2026-03-23 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_profile_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics/doctor_pics/'),
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile_pics/patient_pics/'),
        ),
    ]
