# Generated by Django 6.0.2 on 2026-03-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_doctorprofile_profile_pic_patientprofile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorprofile',
            name='is_hospital_completed',
            field=models.BooleanField(default=False),
        ),
    ]
